# This is a basic workflow to help you get started with Actions
# 发布
name: SharkMvvmPublish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #    branches: [ master ]
    tags: [ 1.* ]
    #  pull_request:
    #    branches: [ master ]
    #    tags: [ 1.* ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: build package
        run: gradle :mvvm:build

      #获取TAG版本
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Publish tools package
          run: gradle :tools:publishToolsPublicationToGitToolsRepository -PTAG_VERSION=${{ steps.get_version.outputs.VERSION }}
          env:
            GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_USER: ${{ github.event.head_commit.committer.username }}

      - name: Publish mvvm package
        run: gradle :mvvm:publishMvvmPublicationToMvvmRepository -PTAG_VERSION=${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.event.head_commit.committer.username }}
